#pragma once

// Please don't change the content of this header, it is auto generated by CMAKE

#define PROJECT_SOURCE_DIR "D:/dev/PhD/CPSC427-Winter2024/A1/cpsc-427-dev-Chicken_Template_2023/template/"
